### ISSUE TITLE
Inf loop? when src file don't exist

### ISSUE THREAD

**Issue by gordio** [docpad/docpad-plugin-raw#11]
```
    plugins:
        raw:
            raw:
                src: 'static'
```

And when `static` directory don't exist I see BI-I-IG log output.
